import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { Header } from '@/components/header';
import { VoiceRecordDialog } from '@/components/voice-record-dialog';

import { ClerkProvider } from '@clerk/nextjs';
import { ConvexClientProvider } from '@/components/convex-client-provider';
import { Toaster } from 'sonner';

const ranadeFont = localFont({
  src: [
    {
      path: '../public/fonts/Ranade-Light.woff',
      weight: '300',
    },
    {
      path: '../public/fonts/Ranade-Regular.woff',
      weight: '400',
    },
    {
      path: '../public/fonts/Ranade-Medium.woff',
      weight: '600',
    },
    {
      path: '../public/fonts/Ranade-Bold.woff',
      weight: '700',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`bg-[#f9fafb]`}>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-screen h-screen">
              <Header />
              <div className="border-b shadow-sm mb-2" />
              <ConvexClientProvider>
                <div className="px-4">{children}</div>
                <VoiceRecordDialog />
              </ConvexClientProvider>
            </main>
          </SidebarProvider>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
