import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
});

const ranadeFont = localFont({
  src: [
    {
      path: '../public/fonts/Ranade-Light.woff',
      weight: '300',
    },
    {
      path: '../public/fonts/Ranade-Regular.woff',
      weight: '400',
    },
    {
      path: '../public/fonts/Ranade-Medium.woff',
      weight: '600',
    },
    {
      path: '../public/fonts/Ranade-Bold.woff',
      weight: '700',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ranadeFont.className}`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full h-full">
            <div className="max-w-6xl mx-auto px-2 xl:px-0">
              <SidebarTrigger />
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
